services:
  shared_postgres:
    container_name: boilerplate-postgres
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=boilerplate
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_DB=boilerplate

  shared_rabbitmq:
    container_name: boilerplate-rabbitmq
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=codely
      - RABBITMQ_DEFAULT_PASS=c0d3ly

  test_server_java:
    container_name: boilerplate-test_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_postgres
      - shared_rabbitmq
    tty: true
